name: Security Scan + Release CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install security tools
        run: |
          pip install pylint bandit

      - name: Run pylint (code quality)
        run: pylint app.py --exit-zero

      - name: Run Bandit (SAST security scan)
        run: bandit -r . --exit-zero

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/python-crypto-app:latest
